apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-telemetry-policy.yaml
  - istio-gateway-telemetry.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: maas-observability
    includeSelectors: false
